### ISSUE TITLE
Cerebral with React and stateless function

### ISSUE THREAD

**Issue by Shroder** [christianalfoni/cerebral#56] opened 2015-08-12 13:49 UTC
I'm using Cerebral with React. I'm running into an issue when using Cerebral without a React Class. Instead of using React.createClass I'm using a stateless function to produce the component.

When the event emitter runs update, the Cerebral mixin function `_mergeInState` is given the wrong reference to "this". "this" is a Cerebral object, and not the component. An error occurs when the script attempts to access this.context.cerebral in `_mergeInState`:

var cerebral = this.context.cerebral;

From troubleshooting I've found that ReactClass binds `this` to the component. Which results in `_mergeInState` keeping the component reference for `this`.

It looks like the chains of events are:
1.) this.signals.signalName(value) is called
2.) Function literal assigned to signalPath.path[signalPath.key] in createSignalMethod is called
3.) emit('update') on EventEmitter from events module is called

EventEmitter is a dependency module that Cerebral uses.

The particular component that triggers this issue can be found [here](https://github.com/Shroder/essential-javascript-links/blob/with-stampit/source/components/formControlsFactory.js).

First I want to confirm if this is a bug. If it's not a bug can you explain why not so I know where to look next?

**Comment by christianalfoni** [comment] 2015-08-12 14:38
Hi @Shroder!

Thanks for reporting this. I see in your example you are bringing in "mixin" twice. Both by composing and using the "mixins" property. Might that be it?

If not, these might just be something Cerebral should handle. Though if it fails with Cerebral, it probably fails with a lot of existing projects. There is nothing special to this mixin really.

But okay, let me know about the composing and using mixin property and we go from there? :-)

**Comment by Shroder** [comment] 2015-08-12 15:24
Hi @christianalfoni,

The mixins property you see is being ignored, at least I'm 99% sure. It's why I'm using the compose method. From what I recall, the mixins property doesn't actually get used. I think it's because React.createClass handles that normally. I'll try to double check this evening.

**Comment by ericelliott** [comment] 2015-08-13 01:22
@Shroder , I think the problem is that **mixins are not supported using the new ES6 class support** (which is also the feature that makes pure functions work).

I wonder if you could wrap Cerebral into a react stamp and compose cerebral with your component. I haven't tried this yet. =)

**Comment by ericelliott** [comment] 2015-08-13 01:23
@Shroder Or just try deleting line 7?

```js
   mixins: [mixin],
```

**Comment by Shroder** [comment] 2015-08-13 13:43
The mixins property definitely isn't being used. Tested out my app without it and got the same error.

It looks like the mixin was moved to cerebral-react-immutable-store? My project is now behind version-wise, so I think I should update my packages to use the most recent versions of all my packages.

I have some other findings with 0.9.0, but I'll first see if it's still relevant after the upgrade.

**Comment by christianalfoni** [comment] 2015-08-13 14:05
Great! Let us know how it went :-)

**Comment by ericelliott** [comment] 2015-08-15 00:37
@christianalfoni Have you tried using cerebral with [react-stampit](https://github.com/stampit-org/react-stampit)?

**Comment by christianalfoni** [comment] 2015-08-15 09:03
Hi there!

did a small test now, and it works just fine it seems?

```js
import {Mixin} from 'cerebral-react-immutable-store';
const MyComp = stampit(React, {
  getStatePaths() {
    return {key: ['path']
  },
  render() {
    return (
      <div>Hello {this.state.key}</div>
    );
  }
}).compose(Mixin);
```

So make sure you import the Mixin correctly, it is a property on the Controller. As it uses the pure Mixin the state will be availalbe on the state object of the component, not props.

If it still does not work I think we have to work on a specific example :-) But yeah, I tried it and it worked on my end

**Comment by ericelliott** [comment] 2015-08-15 09:10
:+1:

**Comment by christianalfoni** [comment] 2015-08-18 18:13
Closing this as it seems to have worked out :-)

**Closed by christianalfoni** 2015-08-18 18:13 UTC
